/**
 * 
 */
package gov.ifms.workflow.util;

/**
 * @author Vivek
 *
 */
public enum WfTrnSubmitSp {

	
	IN_TRN_ID,
	IN_ACTIONCONFIG_ID,
	IN_WF_ACTION_ID,
	IN_ASSIGN_TO_WF_ROLE_ID,
	IN_ASSIGN_TO_USER_ID,
	IN_ASSIGN_TO_POST_ID,
	IN_ASSIGN_TO_POU_ID,
	IN_ASSIGN_TO_OFFICE_ID,
	IN_ASSIGN_TO_BRANCH_ID,
	IN_ASSIGN_TO_GROUP_ID,
	IN_WF_STATUS,
	IN_TRN_STATUS,
	IN_ASSIGN_BY_WF_ROLE_ID,
	IN_ASSIGN_BY_USER_ID,
	IN_ASSIGN_BY_POST_ID,
	IN_ASSIGN_BY_POU_ID,
	IN_ASSIGN_BY_OFFICE_ID,
	IN_ASSIGN_BY_BRANCH_ID,
	IN_ASSIGN_BY_GROUP_ID,
	IN_REMARKS,
	IN_SEND_BACK_FLAG, 
	IN_LEVEL,
	IN_WF_REQ_ID;
}
